[package]
name = "backend-worker"
version = "0.1.0"
edition = "2021"
authors = ["Manpreet113 <manpreet10542@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
worker = { version = "0.7", features = ['d1'] }

